version: '3'
services:
  web_prod:
    build: .
    command: npm run start
    expose:
        - 8000
    ports:
        - "80:8000"
    restart: always
    environment:
        - NODE_ENV=production
        - PORT=8020
