version: "3"
services:
    #################################
    # Setup Mongo container
    #################################
    database:
        image: mongo
        command: mongod --port 27018
        volumes:
            - /data/db:/data/db

    #################################
    # Setup Server container
    #################################
    server:
        build: ./server
        command: npm run start
        volumes:
            - ./server:/usr/src/app
        depends_on:
            - database
        expose:
            - 4000
        ports:
            - 4000:4000
        environment:
            - NODE_ENV=docker
            - CHOKIDAR_USEPOLLING=true

    #################################
    # Setup Client container
    #################################
    client:
        build: ./client
        command: npm run start
        volumes:
            - ./client:/usr/src/app
        links: 
            - server
        depends_on:
            - server
        environment:
            - REACT_ENV=docker
        expose:
            - 3002
        ports:
            - 3002:3000
            - 35729:35729

        
   